name: Custom IP Speed Test with Auto Commit and Custom Params

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC凌晨3点自动运行

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Download CloudflareSpeedTest
      run: |
        curl -L -o cfst.tar.gz https://github.com/XIU2/CloudflareSpeedTest/releases/latest/download/CloudflareST_linux_amd64.tar.gz
        tar -xzf cfst.tar.gz
        chmod +x CloudflareST

    - name: Run speed test with custom IP list and parameters
      run: |
        ./CloudflareST -f my_ips.txt -url https://cs.yoo.cloudns.be/100m -tl 200 -sl 10 -tp 443 -dn 10 -o result.csv

    - name: Generate best_ips.txt from CSV
      run: |
        cut -d, -f1 result.csv | sed '1d' > best_ips.txt
        cat best_ips.txt

    - name: Commit and push best_ips.txt
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if ! git diff --quiet best_ips.txt; then
          git add best_ips.txt
          git commit -m "Auto update best_ips.txt from speed test [skip ci]"
          git push
        else
          echo "No changes to best_ips.txt, skip commit."
        fi
